Repository codesquad-members-2023/be-javascript-cafe-max, pull requests merged in 2023-03, with the labels that each got.

#2 [sully] 학습 계획 작성
  README.md
Labels: documentation, study plan

#4 [Joy] 학습계획 작성
  .idea/misc.xml
  .idea/workspace.xml
  README.md
Labels: documentation

#5 [JAJA] step-1 학습계획
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/p3.iml
  .idea/vcs.xml
  README.md
Labels: study plan, step-1

#6 [Ayaan] 학습계획 작성
  README.md
Labels: study plan

#7 [시오] 학습 계획 작성
  README.md
Labels: study plan

#8 [브루니] 학습계획 작성
  .gitignore
  README.md
Labels: study plan

#10 [지안] step-1 구현
  README.md
  mini-mission/css/root.css
  mini-mission/css/style.css
  mini-mission/js/login.js
  mini-mission/login.html
  mini-mission/sign-in-success.html
  mini-mission/sign-in.html
Labels: study plan, step-1

#11 [네모네모] step-1 회원가입 페이지 구현 및 학습계획 작성
  README.md
  STEP1.md
  STUDY_PLAN.md
  resources/components/header.html
  resources/index.html
  resources/static/css/bootstrap-grid.css
  resources/static/css/bootstrap-grid.css.map
  resources/static/css/bootstrap-grid.min.css
  resources/static/css/bootstrap-grid.min.css.map
  resources/static/css/bootstrap-reboot.css
  resources/static/css/bootstrap-reboot.css.map
  resources/static/css/bootstrap-reboot.min.css
  resources/static/css/bootstrap-reboot.min.css.map
  resources/static/css/bootstrap.css
  resources/static/css/bootstrap.css.map
  resources/static/css/bootstrap.min.css
  resources/static/css/bootstrap.min.css.map
  resources/static/css/common.css
  resources/static/css/header.css
  resources/static/css/reset.css
  resources/static/css/signup.css
  resources/static/js/bootstrap.bundle.js
  resources/static/js/bootstrap.bundle.js.map
  resources/static/js/bootstrap.bundle.min.js
  resources/static/js/bootstrap.bundle.min.js.map
  resources/static/js/bootstrap.js
  resources/static/js/bootstrap.js.map
  resources/static/js/bootstrap.min.js
  resources/static/js/bootstrap.min.js.map
  resources/static/js/common.js
  resources/static/js/signup.js
  resources/user/signup.html
Labels: study plan, step-1

#12 [charlie] step-1 회원가입 구현
  .vscode/settings.json
  README.md
  css/reset.css
  css/screens/login.css
  css/style.css
  js/registerValidator.js
  js/setPlaceholder.js
  login.html
  register1.html
  register2.html
Labels: study plan, step-1

#13 [Fia] 학습 계획 / Step-1 구현
  README.md
  font.css
  form-layout.css
  sign-up.html
  validation.js
Labels: study plan, step-1

#14 [Ape] Step 1 구현
  src/css/signup_form.css
  src/html/signup_form.html
  src/html/signup_success.html
  src/js/signup.js
  src/js/signup_success.js
Labels: study plan, step-1

#15 [감귤] 학습 계획 작성
  README.md
Labels: study plan

#16 [light] Step-1 화면,유효성검사 구현
  README.md
  web_front/css/style.css
  web_front/js/signup.js
  web_front/login/login.html
  web_front/signup/signup.html
  web_front/signup/signupSucess.html
Labels: study plan, step-1

#9 [브루니] 게시판 1단계 - 회원가입
  frontend/html/fragments/header.html
  frontend/html/screens/signup.html
  frontend/js/includeHTML.js
  frontend/js/signup.js
Labels: step-1

#17 [Jwon] 학습 계획 작성 및 step-1 구현
  README.md
  css/style.css
  html/join.html
  html/login.html
  js/join_check.js
Labels: study plan, step-1

#18 [무비] step-1 구현 step-1
  Forum/css/mystyle.css
  Forum/homepage.html
  Forum/js/navbarScript.js
  Forum/js/registrationValidator.js
  Forum/login.html
  Forum/navbar.html
  Forum/registration.html
  Forum/termsAndCoditions.html
Labels: step-1

#19 [브루니] 학습계획 작성
  README.md
Labels: study plan

#20 [나그]: 학습계획서 작성
  README.md
Labels: study plan

#21 [길사] 1단계 학습 계획 작성 및 html 폼 구성
  README.md
  register.html
  script.js
Labels: study plan, step-1

#22 [이안] step-1 구현
  html/login.html
  html/register.html
Labels: step-1

#23 [만두] Step 1 구현
  README.md
  css/auth.css
  html/signIn.html
  html/signUp.html
  js/signUp.js
Labels: study plan, step-1

#24 [파이] 학습계획 작성
  README.md
Labels: study plan

#27 [JAJA] step-1 구현
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/p3.iml
  .idea/vcs.xml
  README.md
  login.html
  register.html
  registerDone.html
Labels: step-1

#28 [light] Step-2 구현
  README.md
  web_front/board/boardwrite.html
  web_front/css/board.css
  web_front/css/layout.css
  web_front/css/main.css
  web_front/css/style.css
  web_front/js/boardwrite.js
  web_front/js/main.js
  web_front/main/main.html
Labels: step-2

#30 [Ape] Step 2 메인 페이지 일부 구현
  README.md
  keyword.md
  src/css/main.css
  src/css/signup_form.css
  src/html/main_board.html
  src/html/signup_form.html
  src/html/signup_success.html
  src/js/dummy_board_data.js
  src/js/main_board.js
  src/js/signup.js
  step-2.md
Labels: step-2

#31 [위즈] 학습계획 작성
  README.md
Labels: study plan

#32 [Albert] Step1
  .gitignore
  README.md
  bullentinboard/Join.html
  bullentinboard/Login.html
  bullentinboard/css/bootstrap.min.css
  bullentinboard/css/bootstrap.min.css.map
Labels: step-1

#33 [보노] 학습계획 작성
  .gitignore
  README.md
  STUDY_PLAN.md
Labels: study plan

#34 [Hana] step-1,2 구현
  .idea/.gitignore
  .idea/be-javascript-cafe-max.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/login.html
  src/main-guest.html
  src/main-member.html
  src/main.js
  src/posting.html
  src/register1.html
  src/register2.html
  src/style.css
  src/validation.js
Labels: step-1, step-2

#36 [light] step - 3 구현
  README.md
  web_front/board/boardinfo.html
  web_front/css/boardinfo.css
  web_front/css/main.css
  web_front/js/boardinfo.js
  web_front/js/signup.js
Labels: step-3

#37 [브루니] 학습계획 작성 및 게시판 2단계 - 메인 페이지 구현
  README.md
  frontend/html/screens/main.html
  frontend/html/screens/posting.html
  frontend/js/main.js
  frontend/js/posting.js
Labels: study plan, step-2

#38 [지안] step-2 페이지 틀 구현
  README.md
  mini-mission/css/login.css
  mini-mission/css/main.css
  mini-mission/css/style.css
  mini-mission/html/login.html
  mini-mission/html/main.html
  mini-mission/html/sign-in-success.html
  mini-mission/html/sign-in.html
  mini-mission/js/login.js
  mini-mission/js/main.js
  mini-mission/js/sign-in-success.js
  mini-mission/js/sign-in.js
  mini-mission/main.html
Labels: study plan, step-2

#39 [charlie] step-2 구현
  README.md
  css/components/button.css
  css/components/topBar.css
  css/screens/login.css
  css/screens/mainPage.css
  css/screens/posting.css
  css/style.css
  js/mainPage.js
  js/postingValidator.js
  login.html
  mainPage.html
  posting.html
  register1.html
  register2.html
Labels: step-2

#41 [네모네모] step-2 구현
  README.md
  STEP1.md
  STEP2.md
  STUDY_PLAN.md
  resources/components/head_header.html
  resources/components/header.html
  resources/index.html
  resources/static/css/board.css
  resources/static/js/jquery-3.6.4.js
  resources/static/js/post_generator.js
  resources/static/js/post_pagination.js
  resources/user/login.html
  resources/user/signup.html
  resources/user/signup_success.html
Labels: step-2

#42 [감귤] STEP - 1 구현중
  .idea/.gitignore
  .idea/jscafe.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  CSS/style.css
  HTML/Signin.html
  HTML/Signup.html
  JS/signup.js
  README.md
Labels: step-1

#44 [Fia] 학습 계획 / Step-2 구현
  README.md
  header.css
  main.css
  main.html
  post.css
  post.html
  sign-up.css
  sign-up.html
  validation.js
Labels: study plan, step-2

#45 [시오] step1 구현
  README.md
  signUp.html
  signUp.js
Labels: step-1

#35 [Joy] step-1
  .idea/vcs.xml
  .idea/workspace.xml
  Domain.js
  Join.html
  JoinComplete.html
  Main.html
  README.md
  mainStyle.css
  style.css
Labels: step-1

#43 [이안] step-2 구현
  html/list.html
  html/login.html
  html/register.html
  html/write.html
Labels: step-2

#48 [브루니] 학습계획 작성
  README.md
Labels: study plan

#49 [Fia] 학습 계획 / Step-2 JSON 데이터 사용하여 구현
  .gitignore
  README.md
  data.json
  forum.js
  main.css
  main.html
Labels: study plan, step-2

#50 [나그]: 카페 회원가입 페이지 작성
  Register.html
Labels: step-1

#52 [보노] step-1 구현중
  css/style.css
  html/login.html
  html/signup.html
  html/signup_success.html
Labels: step-1

#53 [네모네모] step-3 html 페이지 구현
  STEP1.md
  STUDY_PLAN.md
  resources/board/detail.html
  resources/board/write.html
  resources/static/css/detail.css
  resources/static/css/write.css
  resources/static/js/login.js
  resources/static/js/post_generator.js
  resources/static/js/post_pagination.js
  resources/static/js/signup.js
  resources/static/js/signup_success.js
  resources/static/js/write.js
  resources/user/login.html
Labels: step-3

#57 [light] step - 4 구현중
  README.md
  web_front/board/boardinfo.html
  web_front/css/main.css
  web_front/js/boardinfo.js
  web_front/js/data.js
  web_front/js/login.js
  web_front/js/main.js
  web_front/login/login.html
  web_front/main/main.html
Labels: documentation, step-3

#58 [Ape] Step 2 구현
  src/css/main.css
  src/css/write_from.css
  src/html/main_board.html
  src/html/signup_form.html
  src/html/signup_success.html
  src/html/write_form.html
  src/img/peppermint.jpg
  src/js/common.js
  src/js/main_board.js
  src/js/write_form.js
  step-2.md
Labels: step-2

#59 [위즈] Step-2 구현
  src/dataValidation.js
  src/jsondata.js
  src/login.html
  src/main-guest.html
  src/main-member.html
  src/memberList.html
  src/posting-style.css
  src/posting.html
  src/signUp.html
  src/signUpCompleted.html
  src/style.css
Labels: step-2

#60 [ Albert ] step3-구현
  bullentinboard/Main.html
  bullentinboard/PostDetail.html
  bullentinboard/Posting.html
Labels: step-3

#61 [네모네모] step-1 구현
  FEEDBACK.md
  README.md
  STEP1.md
  STEP2.md
  STUDY_PLAN.md
  resources/components/header.html
  resources/index.html
  resources/static/css/common.css
  resources/static/css/header.css
  resources/static/css/index.css
  resources/static/js/board.js
  resources/static/js/header.js
  resources/static/js/index.js
  resources/static/js/login.js
  resources/static/js/logout.js
  resources/static/js/member.js
  resources/static/js/members.js
  resources/static/js/page.js
  resources/static/js/post.js
  resources/static/js/post_generator.js
  resources/static/js/posts.js
  resources/static/js/signup.js
  resources/static/js/signup_success.js
  resources/static/json/post.json
  resources/user/login.html
  resources/user/signup.html
  resources/user/signup_success.html
  페이지네이션.pptx
Labels: step-1

#62 [위즈] Step-3 구현
  README.md
  src/css/posting-style.css
  src/css/style.css
  src/html/login.html
  src/html/main-guest.html
  src/html/main-member.html
  src/html/memberList.html
  src/html/postDetail.html
  src/html/posting.html
  src/html/signUp.html
  src/html/signUpCompleted.html
  src/js/data.js
  src/js/dataValidation.js
  src/js/jsondata.js
  src/js/post.js
  src/posting-style.css
Labels: step-3

#63 [light] step-4 기능 구현
  web_front/js/boardinfo.js
  web_front/js/boardwrite.js
  web_front/js/data.js
  web_front/js/main.js
Labels: enhancement, step-3

#64 [네모네모] step-2 구현
  STEP2.md
  STUDY_PLAN.md
  resources/board/detail.html
  resources/board/write.html
  resources/index.html
  resources/static/js/board.js
  resources/static/js/common.js
  resources/static/js/detail.js
  resources/static/js/header.js
  resources/static/js/index.js
  resources/static/js/login.js
  resources/static/js/post.js
  resources/static/js/post_generator.js
  resources/static/js/posts.js
  resources/static/js/signup.js
  resources/static/js/write.js
  resources/static/json/post.json
  resources/user/login.html
Labels: step-2

#65 [light] step-4 GitHub 배포 완료
  README.md
  board/boardinfo.html
  board/boardwrite.html
  css/board.css
  css/boardinfo.css
  css/layout.css
  css/main.css
  css/style.css
  index.html
  js/boardinfo.js
  js/boardwrite.js
  js/data.js
  js/login.js
  js/main.js
  js/signup.js
  main/main.html
  signup/signup.html
  signup/signupSucess.html
  web_front/js/data.js
Labels: documentation, step-3

#66 [네모네모] Step3-구현
  STUDY_PLAN.md
  index.html
  resources/board/detail.html
  resources/board/write.html
  resources/components/header.html
  resources/static/css/detail.css
  resources/static/js/comment.js
  resources/static/js/comments.js
  resources/static/js/common.js
  resources/static/js/detail.js
  resources/static/js/index.js
  resources/static/js/login.js
  resources/static/js/logout.js
  resources/static/js/member.js
  resources/static/js/members.js
  resources/static/js/page.js
  resources/static/js/post.js
  resources/static/js/posts.js
  resources/static/js/signup.js
  resources/static/js/signup_success.js
  resources/static/js/write.js
  resources/static/json/post.json
  resources/user/login.html
  resources/user/signup.html
  resources/user/signup_success.html
Labels: step-3
